import Foundation

extension Tron {
    enum Block: String {
        case
        sourcepoint,
        crwdcntrl,
        tags,
        pubmatic,
        ads,
        indexww,
        casalemedia,
        googlesyndication,
        safeframe,
        hotjar,
        vars,
        demdex,
        adalliance,
        yieldlab,
        sparwelt,
        adrtx,
        criteo,
        interactive,
        dwcdn,
        doubleclick,
        googleads,
        adition,
        openx,
        guim,
        googleadservices,
        dianomi,
        platform,
        googleapis,
        imasdk,
        addthis,
        emsservice,
        rubiconproject,
        creativecdn,
        googletagservices,
        media,
        flashtalking,
        optimizely,
        medtargetsystem,
        tr,
        cloudfront,
        cedexis,
        scorecardresearch,
        bounceexchange,
        accounts,
        ufpcdn,
        onclickgenius,
        appsflyer,
        onmarshtompor,
        rakamu,
        bongacams,
        bngpt,
        adsco,
        bet365,
        the_ozone_project = "the-ozone-project",
        amazon_adsystem = "amazon-adsystem",
        google_analytics = "google-analytics",
        cedexis_radar = "cedexis-radar",
        user_shield = "user-shield"
    }
}
