import Foundation

extension Tron {
    static let partial = Set([
                                "sourcepoint",
                                "crwdcntrl",
                                "the-ozone-project",
                                "tags",
                                "pubmatic",
                                "ads",
                                "indexww",
                                "casalemedia",
                                "googlesyndication",
                                "safeframe",
                                "hotjar",
                                "vars",
                                "demdex",
                                "adalliance",
                                "yieldlab",
                                "sparwelt",
                                "adrtx",
                                "criteo",
                                "interactive",
                                "dwcdn",
                                "doubleclick",
                                "googleads",
                                "adition",
                                "openx",
                                "guim",
                                "googleadservices",
                                "dianomi",
                                "platform",
                                "googleapis",
                                "imasdk",
                                "addthis",
                                "ampproject",
                                "emsservice",
                                "amazon-adsystem",
                                "rubiconproject",
                                "creativecdn",
                                "googletagservices",
                                "media",
                                "flashtalking"])
}
